name: 755c9df7b9e3837d5eb7d80ee6bab896
channels:
  - pytorch
  - nvidia
dependencies:
  - cudatoolkit=11.1.74
  - python=3.6.9
  - pytorch=1.9.0
  - tensorboard=1.15.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
